Rack
danilpanshin/rack pull request #1
Opened 2018-03-31 16:04 UTC by danilpanshin

2018-03-31 16:05 UTC, danilpanshin commented on middleware/logger.rb
> +require 'logger'
оставил логгер, чтобы смотреть ошибки

2018-04-01 13:43 UTC, psylone requested changes

2018-04-01 13:43 UTC, psylone commented on app.rb
> +    @path = env["REQUEST_PATH"]
Используй объект запроса `Rack::Request`.

2018-04-01 13:43 UTC, psylone commented on app.rb
> +    @path == "/time"
Могут быть и другие пути поэтому лучше использовать `case-when-else-end`.

2018-04-01 13:43 UTC, psylone commented on app.rb
> +    [status, headers, body]
У тебя получилось так что логика обработчика размазывается в каждом из методов `status`, `headers` и `body`. А если поведение изменится или усложнится? Например, появится календарь или нужно будет сохранять метку времени. Расширять текущее решение довольно трудно.

2018-04-01 13:43 UTC, psylone commented on app.rb
> +    [status, headers, body]
Используй такой подход. Rack-приложение, то есть класс `App` отвечает строго за обработку запроса. Здесь мы принимаем `env` (окружение запроса) и определяем какому обработчику его передать. В данном случае в качестве обработчика можно использовать метод. Полуается что-то вроде этого:

```ruby
def call(env)
  request = Rack::Request.new(env)

  case <path>
  when <one>
    handle_one_request
  when <two>
    handle_two_request
  else
    not_found
  end
end

def handle_one_request
  <code>
  # Rack response
  []
end
```

Следующий момент заключается в том что форматирование времени - отдельная задача за которую должна отвечать отдельная абстракция, например, Ruby-класс. Этот класс ничего не должен знать о том где он будет использоваться: в Rack-приложении, консоли, Rails-приложении или Ruby-проекте.

2018-04-01 13:43 UTC, psylone commented on app.rb
> +    [status, headers, body]
Таким образом, тебе необходимо разделить непосредственно Rack-приложение и задачу форматирования времени.

2018-04-01 14:30 UTC, danilpanshin commented on app.rb
> +    @path == "/time"
вот тут не понял. в задании же сказано, что "При запросе на любой другой URL необходимо возвращать ответ с кодом статуса 404"

2018-04-01 14:33 UTC, danilpanshin commented on app.rb
> +    @path == "/time"
то есть, как я понимаю, путь может быть только Time

2018-04-02 17:03 UTC, danilpanshin commented on Gemfile
> +source 'https://rubygems.org'
добавил консоль, чтобы посмотреть ошибки и сразу стало ясно, где нужно поправить, без нее вслепую было сложно

2018-04-02 17:03 UTC, danilpanshin commented on time_formatter.rb
> -    return_time
нужно было убрать этот метод из инишиалайз и всё заработало

2018-04-03 09:29 UTC, psylone approved these changes

2018-04-03 09:29 UTC, psylone commented on app.rb
> +    @user_format = Rack::Utils.parse_nested_query(@request.query_string).values.join.split(",")
Правила разбора параметров лучше определить в том классе который ими пользуется. То есть мы передаём в конструктор `@request.params`, а класс уже сам знает что с этим нужно делать.

2018-04-03 09:29 UTC, psylone commented on app.rb
> +      handle_one_request
`handle_time_request`.

2018-04-03 09:29 UTC, psylone commented on app.rb
> +    [@status, headers, @body]
Удобно также использовать объект класса `Rack::Response`.

2018-04-03 11:34 UTC, merged

2018-04-07 17:13 UTC, psylone commented on app.rb
> +    @path == "/time"
В нашем задании да, но если нужно будет расширить логику и добавить, например, путь `/date`, то с `case` это будет сделать проще.